document.writeln("<div id=\"\" class=\"footer\">");
document.writeln("			<div class=\"two-all top\">");
document.writeln("				<ul>");
document.writeln("					<li class=\"left\">");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><a href='"+webRoot + "/system/companyIntroduce/init'><span class='textCN'>关于联信</span><span class='textEN'>About Us</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/companyIntroduce/init'><span class='textCN'>联信业务</span><span class='textEN'>Services</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/companyIntroduce/init'><span class='textCN'>社会责任</span><span class='textEN'>Social Awareness</span></a></li>");
document.writeln("							<li class='textCN'><a href='"+webRoot + "/system/companyIntroduce/init'><span>加入联信</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/companyIntroduce/init'><span class='textCN'>联系我们</span><span class='textEN'>Contact Us</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><a href='"+webRoot + "/system/companyIntroduce/init'><span class='textCN'>企业介绍</span><span class='textEN'>About Us</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/produce/init?proType=1&yqType=0'><span class='textCN'>国内逾期账款管理</span><span class='textEN'>Domestic Debt Collection</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><a href='"+webRoot + "/system/companyCulture/init'><span class='textCN'>联信文化</span><span class='textEN'>Corporate Culture</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/produce/init?proType=1&yqType=1'><span class='textCN'>国际逾期账款管理</span><span class='textEN'>International Debt Collection</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><a href='"+webRoot + "/system/companyDynamic/init'><span class='textCN'>联信动态</span><span class='textEN'>Corporate News</span></a></li>");
document.writeln("							<li><a href='"+webRoot + "/system/produce/init?proType=0'><span class='textCN'>征信业务</span><span class='textEN'>Credit Services</span></a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\"middle\">");
document.writeln("						<ul class=\"middleL\">");
document.writeln("						    <ul class=\"leftSmall\">");
document.writeln("							    <li><span class='textCN'>咨询电话</span><span class='textEN'>Hotline</span></li>");
document.writeln("							    <li><span class='textCN'>投诉电话</span><span class='textEN'>Complaint Hotline</span></li>");
document.writeln("						    </ul>");
document.writeln("						    <ul class=\"leftSmall\">");
document.writeln("							    <li>0532-82881676</li>");
document.writeln("							    <li>0532-82022612</li>");
document.writeln("						    </ul>");
document.writeln("						    <ul class=\"leftSmall\">");
document.writeln("							    <li><span class='textCN'>邮箱</span><span class='textEN'>Email</span></li>");
document.writeln("							    <li><span class='textCN'>友情链接</span><span class='textEN'>Link</span></li>");
document.writeln("						    </ul>");
document.writeln("						    <ul class=\"leftSmall\">");
document.writeln("							    <li><a href=\"mailto:culture@inter-credit.net\">culture@inter-credit.net</a></li>");
document.writeln("							    <li><a href=\"http://www.lianxin-tech.com/\"><span class='textCN'>联信科技</span><span class='textEN'>Inter-Credit</span></a></li>");
document.writeln("						    </ul>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"middleR\">");
document.writeln("							<li><img class=\"workingHoursImg\" src='"+webRoot+"/images/index/f7.png\'></li>");
document.writeln("							<li class=\"workingHours\"><span class='textCN'>工作日</span> 9:00-18:00</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\"right\">");
document.writeln("						<div><img src='"+webRoot+"/images/index/f6.png\'></div>");
document.writeln("						<p><span class='textCN'>公众号</span><span class='textEN'>WeChat Official Account</span> QDlianxin1997</p>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\"line\"></div>");
document.writeln("			<div class=\"footer-all\">");
document.writeln("				<ul>");
document.writeln("					<li><img src='"+webRoot+"/images/index/f5.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/images/index/f1.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/images/index/f2.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/images/index/f3.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/images/index/f4.png\'></li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\"footer-bottom textCN\">© 2018 青岛联信商务咨询有限公司 版权所有 鲁ICP备06004466号-1</div>");
document.writeln("		</div>");