document.writeln("<div class=\"header\">");
document.writeln("            <div class=\"imgBoxlogo textCN\"><a href='"+webRoot + "/system/desktop/init'><img src='"+webRoot+"/images/index/logo1.png'></a></div>");
document.writeln("            <div class=\"imgBoxlogo textEN\"><a href='"+webRoot + "/system/desktop/init'><img src='"+webRoot+"/images/index/logo1-EN.png'></a></div>");
document.writeln("			<ul class=\"nav\">");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href='"+webRoot + "/system/desktop/init'>首页</a>");
document.writeln("					<a class='textEN' href='"+webRoot + "/system/desktop/init'>Home</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href='"+webRoot + "/system/companyIntroduce/init'>关于联信</a>");
document.writeln("					<a class='textEN' href='"+webRoot + "/system/companyIntroduce/init'>About Us</a>");
document.writeln("					<ul class=\"second-nav\">");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyIntroduce/init'>企业介绍</a>");
document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyIntroduce/init'>About Us</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyCulture/init'>联信文化</a>");
document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyCulture/init'>Corporate Culture</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyDynamic/init'>联信动态</a>");
document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyDynamic/init'>Corporate News</a>");
document.writeln("						</li>");
//document.writeln("						<li>");
//document.writeln("							<a class='textCN' href='"+webRoot + "/system/aboutUs/init#main-five'>发展历程</a>");
//document.writeln("							<a class='textEN' href='"+webRoot + "/system/aboutUs/init#main-five'>History</a>");
//document.writeln("						</li>");
//document.writeln("						<li>");
//document.writeln("							<a class='textCN' href='"+webRoot + "/system/aboutUs/init#main-six'>荣誉资质</a>");
//document.writeln("							<a class='textEN' href='"+webRoot + "/system/aboutUs/init#main-six'>Honor</a>");
//document.writeln("						</li>");
//document.writeln("						<li>");
//document.writeln("							<a class='textCN' href='"+webRoot + "/system/aboutUs/init#main-seven'>合作伙伴</a>");
//document.writeln("							<a class='textEN' href='"+webRoot + "/system/aboutUs/init#main-seven'>Partners</a>");
//document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href='"+webRoot + "/system/produce/init'>联信业务</a>");
document.writeln("					<a class='textEN' href='"+webRoot + "/system/produce/init'>Services</a>");
document.writeln("					<ul class=\"second-nav\">");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/produce/init?proType=1&yqType=0'>国内逾期账款管理</a>");
document.writeln("							<a class='textEN' href='"+webRoot + "/system/produce/init?proType=1&yqType=0'>Domestic Debt Collection</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/produce/init?proType=1&yqType=1'>国际逾期账款管理</a>");
document.writeln("						    <a class='textEN' href='"+webRoot + "/system/produce/init?proType=1&yqType=1'>International Debt Collection</a>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href='"+webRoot + "/system/produce/init?proType=0'>征信业务</a>");
document.writeln("							<a class='textEN' href='"+webRoot + "/system/produce/init?proType=0'>Credit Services</a>");
document.writeln("						</li>");
//document.writeln("						<li>");
//document.writeln("							<a class='textCN' href=\"http://www.lianxin-tech.com\" target=\"_Blank\">联信科技</a>");
//document.writeln("							<a class='textEN' href=\"http://www.lianxin-tech.com\" target=\"_Blank\">Inter-Credit</a>");
//document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
// document.writeln("				<li>");
// document.writeln("					<a class='textCN' href='"+webRoot + "/system/companyDynamic/init'>联信动态</a>");
// document.writeln("					<a class='textEN' href='"+webRoot + "/system/companyDynamic/init'>Newsletters</a>");
// document.writeln("					<ul class=\"second-nav\">");
// document.writeln("						<li>");
// document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyDynamic/init?type=0'>联信时讯</a>");
// document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyDynamic/init?type=0'>Latest News</a>");
// document.writeln("						</li>");
// document.writeln("						<li>");
// document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyDynamic/init?type=1'>行业新闻</a>");
// document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyDynamic/init?type=1'>Industry news</a>");
// document.writeln("						</li>");
// document.writeln("						<li>");
// document.writeln("							<a class='textCN' href='"+webRoot + "/system/companyDynamic/init?type=2'>联信Style</a>");
// document.writeln("							<a class='textEN' href='"+webRoot + "/system/companyDynamic/init?type=2'>Inter-Credit Style</a>");
// document.writeln("						</li>");
// document.writeln("					</ul>");
// document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href='"+webRoot + "/system/social/init?isTop=0'>社会责任</a>");
document.writeln("					<a class='textEN' href='"+webRoot + "/system/social/init'>CSR</a>");
document.writeln("				</li>");
document.writeln("				<li class='textCN'>");
document.writeln("					<a href='"+webRoot + "/system/recruit/init'>加入联信</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href='"+webRoot + "/system/contactUs/init'>联系我们</a>");
document.writeln("					<a class='textEN' href='"+webRoot + "/system/contactUs/init'>Contact Us</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<div class=\"language\">");
document.writeln("				<div class=\"languageLine\"></div>");
document.writeln("				<a href=\"javascript:;\"><span class='textCN'>LANGUAGE</span><span class='textEN'>语言</span>");
document.writeln("				<ul><li>EN</li><li>中文</li>");
document.writeln("				</ul></a>");
document.writeln("			</div>");
document.writeln("		</div>");
