document.writeln("<div id=\"\" class=\"footer\">");
document.writeln("			<div class=\"two-all top\">");
document.writeln("				<ul>");
document.writeln("					<li class=\"left\">");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><span class='textCN'>关于我们</span></li>");
document.writeln("							<li><a href=''><span class='textCN'>企业简介</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>企业文化</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>发展历程</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>荣誉资质</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>合作伙伴</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><span class='textCN'>产品服务</span></li>");
document.writeln("							<li><a href=''><span class='textCN'>征信业务</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>逾期账款管理</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>联信科技</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><span class='textCN'>联信动态</span></li>");
document.writeln("							<li><a href=''><span class='textCN'>联信时讯</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>行业新闻</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>联信Style</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>社会责任</span></a></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"leftSmall\">");
document.writeln("							<li><span class='textCN'>加入我们</span></li>");
document.writeln("							<li><a href=''><span class='textCN'>校园招聘</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>社会招聘</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>储备人才库</span></a></li>");
document.writeln("							<li><a href=''><span class='textCN'>联系我们</span></a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\"middle\">");
document.writeln("						<ul class=\"middleL\">");
document.writeln("							<li><img src='"+webRoot+"/img/images/index/f7.png\'></li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\"middleR\">");
document.writeln("							<li><span class='textCN'>咨询电话</span></li>");
document.writeln("							<li class=\"fontRE\">");
document.writeln("								<ul>");
document.writeln("									<li>0532-82881676</li>");
document.writeln("									<li class=\"grayfont\"><span class='textCN'>工作日</span> 9:00-18:00</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li><span class='textCN'>邮箱</span></li>");
document.writeln("							<li>culture@inter-credit.net</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\"right\">");
document.writeln("						<div><img src='"+webRoot+"/img/images/index/f6.png\'></div>");
document.writeln("						<div><p class='textCN'>公众号</p> QDlianxin1997</div>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\"line\"></div>");
document.writeln("			<div class=\"footer-all\">");
document.writeln("				<ul>");
document.writeln("					<li><img src='"+webRoot+"/img/images/index/f5.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/img/images/index/f1.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/img/images/index/f2.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/img/images/index/f3.png\'></li>");
document.writeln("					<li><img src='"+webRoot+"/img/images/index/f4.png\'></li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\"footert-bottom textCN\">© 2018 青岛联信商务咨询有限公司 版权所有 鲁ICP备06004466号-1</div>");
document.writeln("		</div>");