document.writeln("<div class=\"header\">");
document.writeln("            <div class=\"imgBoxlogo textCN\"><a href=''><img src='"+webRoot+"/img/images/index/logo1.png'></a></div>");
document.writeln("            <div class=\"imgBoxlogo textEN\"><a href=''><img src='"+webRoot+"/img/images/index/logo1-EN.png'></a></div>");
document.writeln("			<ul class=\"nav\">");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>首页</a>");
document.writeln("					<a class='textEN' href=''>Home</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>关于联信</a>");
document.writeln("					<a class='textEN' href=''>About Us</a>");
document.writeln("					<ul class=\"second-nav\">");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>企业简介</a>");
document.writeln("							<a class='textEN' href=''>About Us</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>企业文化</a>");
document.writeln("							<a class='textEN' href=''>Corporate Culture</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>发展历程</a>");
document.writeln("							<a class='textEN' href=''>History</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>荣誉资质</a>");
document.writeln("							<a class='textEN' href=''>Honor</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>合作伙伴</a>");
document.writeln("							<a class='textEN' href=''>Partners</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>我们的业务</a>");
document.writeln("					<a class='textEN' href=''>Services</a>");
document.writeln("					<ul class=\"second-nav\">");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>逾期账款管理</a>");
document.writeln("							<a class='textEN' href=''>Debt Collection</a>");
document.writeln("							<ul class=\"third-nav\">");
document.writeln("								<li>");
document.writeln("									<a class='textCN' href=''>国内逾期账款管理</a>");
document.writeln("									<a class='textEN' href=''>Domestic Debt Collection</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a class='textCN' href=''>国际逾期账款管理</a>");
document.writeln("									<a class='textEN' href=''>International Debt Collection</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>征信业务</a>");
document.writeln("							<a class='textEN' href=''>Credit Services</a>");
document.writeln("						</li>");
//document.writeln("						<li>");
//document.writeln("							<a class='textCN' href=\"http://www.lianxin-tech.com\" target=\"_Blank\">联信科技</a>");
//document.writeln("							<a class='textEN' href=\"http://www.lianxin-tech.com\" target=\"_Blank\">Inter-Credit</a>");
//document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>联信动态</a>");
document.writeln("					<a class='textEN' href=''>Newsletters</a>");
document.writeln("					<ul class=\"second-nav\">");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>联信时讯</a>");
document.writeln("							<a class='textEN' href=''>Latest News</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>行业新闻</a>");
document.writeln("							<a class='textEN' href=''>Industry news</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a class='textCN' href=''>联信Style</a>");
document.writeln("							<a class='textEN' href=''>Inter-Credit Style</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>社会责任</a>");
document.writeln("					<a class='textEN' href=''>Social Awareness</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>加入联信</a>");
document.writeln("					<a class='textEN' href=''>Join Us</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a class='textCN' href=''>联系我们</a>");
document.writeln("					<a class='textEN' href=''>Contact Us</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
/*document.writeln("			<div class=\"language\">");
document.writeln("				<div class=\"languageLine\"></div>");
document.writeln("				<a href=\"javascript:;\">LANGUAGE");
document.writeln("				<ul><li>ENGLISH</li><li>中文</li>");
document.writeln("				</ul></a>");
document.writeln("			</div>");*/
document.writeln("		</div>");
